# Generated by Django 4.1.5 on 2023-02-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catsapps", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Name",
            new_name="Names",
        ),
    ]
