# Generated by Django 4.1.5 on 2023-02-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catsapps", "0002_rename_name_names"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Names",
            new_name="Name",
        ),
    ]
