# Generated by Django 4.1.5 on 2023-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catsapps", "0003_rename_names_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="breed",
            field=models.CharField(default="1", max_length=15),
            preserve_default=False,
        ),
    ]
